version: '3.8'

services:
  db:
    container_name: docker-mca-db
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db-postgres
    ports:
      - "5432:5432"
    volumes:
      - volume_name:/var/lib/postgresql/data 

volumes:
  volume_name:
